### ISSUE TITLE
Pattern Validator Doesn't Work For Underscore ( _ )

### ISSUE THREAD

**Issue by adithyaakrishna** [ArefMozafari/flutter_pw_validator#1]
**Description:** Underscore isn't working or taking as a special character in the validator
**Screenshot:** 
![image](https://user-images.githubusercontent.com/23498248/112722056-55c1da00-8f2d-11eb-8372-e1c6bfb9d51b.png)
**Fix:** Add _ to RegExp in the Validator.dart file

**Comment by ArefMozafari** [comment]
PR merged.

**Comment by adithyaakrishna** [comment]
Thanks @ArefMozafari 🎉
