### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by ramluro1** [ArefMozafari/flutter_pw_validator#13]
I have implemented the PW Validator and  I am getting this error with every letter typed into the password field

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for TextEditingController:
setState() called after dispose(): _FlutterPwValidatorState#095a5(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

**Comment by ArefMozafari** [comment]
Which version of flutter_pw_validator are you using? Could you please post your code?

**Comment by ramluro1** [comment]
I am using 1.3.0. Here is my code:

`import 'package:evnteo_pro/backend/auth/auth_util.dart';
import 'package:evnteo_pro/backend/backend.dart';
import 'package:evnteo_pro/flutter_flow/flutter_flow_icon_button.dart';
import 'package:evnteo_pro/flutter_flow/flutter_flow_theme.dart';
import 'package:evnteo_pro/flutter_flow/flutter_flow_widgets.dart';
import 'package:flutter/material.dart';
import 'package:evnteo_pro/screens/components/custom_textfield.dart';
import 'package:flutter_pw_validator/flutter_pw_validator.dart';

class OnboardingEmailSignupWidget extends StatefulWidget {
  const OnboardingEmailSignupWidget({Key key}) : super(key: key);

  @override
  _OnboardingEmailSignupWidgetState createState() =>
      _OnboardingEmailSignupWidgetState();
}

class _OnboardingEmailSignupWidgetState
    extends State<OnboardingEmailSignupWidget> {

  final formKey = GlobalKey<FormState>();
  final scaffoldKey = GlobalKey<ScaffoldState>();

  TextEditingController emailTextController;
  TextEditingController mobileNumTextController;
  TextEditingController passwordTextController;
  TextEditingController confirmPasswordTextController;

  bool checkboxListTileValue;
  bool passwordVisibility1;
  bool passwordVisibility2;

  @override
  void initState() {
    super.initState();

    emailTextController = TextEditingController();
    mobileNumTextController = TextEditingController();
    passwordTextController = TextEditingController();
    confirmPasswordTextController = TextEditingController();
    passwordVisibility1 = false;
    passwordVisibility2 = false;
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: formKey,
      child: Scaffold(
        key: scaffoldKey,
        appBar: AppBar(
          backgroundColor: FlutterFlowTheme.dark400,
          automaticallyImplyLeading: false,
          leading: FlutterFlowIconButton(
            borderColor: Colors.transparent,
            borderRadius: 30,
            borderWidth: 1,
            buttonSize: 60,
            icon: Icon(
              Icons.arrow_back_rounded,
              color: FlutterFlowTheme.tertiaryColor,
              size: 30,
            ),
            onPressed: () async {
              Navigator.pop(context);
            },
          ),
          actions: [],
          centerTitle: false,
          elevation: 0,
        ),
        backgroundColor: Color(0xFFF1F4F8),
        body: SafeArea(
          child: Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 16, 16, 16),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Text(
                      'Set up your account',
                      style: FlutterFlowTheme.title3,
                    ),
                  ],
                ),
              ),
              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 16),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded(
                      child: Text(
                        'Customers will contact you using the following contact information',
                        style: FlutterFlowTheme.subtitle2,
                      ),
                    ),
                  ],
                ),
              ),
              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 8),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded(child:
                        CustomTextFieldWidget(
                          controller: emailTextController,
                          labelText: 'Email',
                          textInputType: TextInputType.emailAddress,
                          minLength: 7,
                        )
                    ),
                  ],
                ),
              ),

              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 8),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded( child:
                      CustomTextFieldWidget(
                        controller: mobileNumTextController,
                        labelText: 'Mobile number',
                        textInputType: TextInputType.phone,
                        minLength: 10,
                      )
                    ),
                  ],
                ),
              ),


              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(10, 0, 16, 0),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded(
                      child: CheckboxListTile(
                        value: checkboxListTileValue ??= true,
                        onChanged: (newValue) =>
                            setState(() => checkboxListTileValue = newValue),
                        title: Text(
                          'Enable text messages',
                          style: FlutterFlowTheme.bodyText1.override(
                            fontFamily: 'Roboto',
                            color: FlutterFlowTheme.dark400,
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                        tileColor: FlutterFlowTheme.background,
                        activeColor: FlutterFlowTheme.secondary600,
                        checkColor: Colors.white,
                        dense: true,
                        controlAffinity: ListTileControlAffinity.leading,
                      ),
                    ),
                  ],
                ),
              ),
              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 8),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded(
                      child: Text(
                        'By enabling text messages, you authorize Evnteo to send you automated text messages. You can opt out at anytime.',
                        style: FlutterFlowTheme.bodyText2.override(
                          fontFamily: 'Roboto',
                          //fontSize: 12,
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              // Password
              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 8),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded( child:
                        new TextFormField(
                          controller: passwordTextController,
                          obscureText: !passwordVisibility1,
                          decoration: InputDecoration(
                            labelText: 'Password',
                            labelStyle: FlutterFlowTheme.bodyText1.override(
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w300,
                            ),
                            enabledBorder: UnderlineInputBorder(
                              borderSide: BorderSide(
                                color: FlutterFlowTheme.grayIcon400,
                                width: 1,
                              ),
                              borderRadius: BorderRadius.circular(0),
                            ),
                            focusedBorder: UnderlineInputBorder(
                              borderSide: BorderSide(
                                color: FlutterFlowTheme.grayIcon400,
                                width: 1,
                              ),
                              borderRadius: BorderRadius.circular(0),
                            ),
                            contentPadding:
                            EdgeInsetsDirectional.fromSTEB(0, 8, 0, 8),
                            suffixIcon: InkWell(
                              onTap: () => setState(
                                    () => passwordVisibility1 = !passwordVisibility1,
                              ),
                              child: Icon(
                                passwordVisibility1
                                    ? Icons.visibility_outlined
                                    : Icons.visibility_off_outlined,
                                color: Color(0xFF757575),
                                size: 22,
                              ),
                            ),
                          ),
                          style: FlutterFlowTheme.bodyText1.override(
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w300,
                          ),
                          keyboardType: TextInputType.visiblePassword,
                          validator: (val) {
                            if (val.isEmpty) {
                              return 'Password missing';
                            }
                            if (val.length < 6) {
                              return 'Password too short';
                            }
                            return null;
                          },
                        ),
                    ),
                  ],
                ),
              ),

              Padding(
                  padding: EdgeInsetsDirectional.fromSTEB(16, 4, 16, 4),
                  child: Row(
                    children: [
                      Theme(
                        data: ThemeData(
                            fontFamily: 'Roboto',
                            splashColor: Colors.yellow,
                         ),
                        child: new FlutterPwValidator(
                          controller: passwordTextController,
                          minLength: 8,
                          uppercaseCharCount: 2,
                          numericCharCount: 3,
                          specialCharCount: 1,
                          width: 350,
                          height: 120,
                          onSuccess: () {
                            print('password success');
                          }
                        ),
                      )
                    ],
                  )
              ),
              
              Spacer(),

              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(16, 16, 16, 8),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    Expanded(
                      child: Text(
                        'By clicking \'Sign up\', I agree to the Terms of User and the Privacy Policy.',
                        style: FlutterFlowTheme.bodyText1.override(
                          fontFamily: 'Roboto',
                          fontSize: 12,
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              Padding(
                padding: EdgeInsetsDirectional.fromSTEB(0, 16, 0, 16),
                child: Row(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    FFButtonWidget(
                      onPressed: () async {
                        if (!formKey.currentState.validate()) {
                          return;
                        }
                        // if (passwordTextController.text !=
                        //     confirmPasswordTextController.text) {
                        //   ScaffoldMessenger.of(context).showSnackBar(
                        //     SnackBar(
                        //       content: Text(
                        //         "Passwords don't match!",
                        //       ),
                        //     ),
                        //   );
                        //   return;
                        // }

                        print(emailTextController.text);
                        print(mobileNumTextController.text);
                        print(passwordTextController.text);


                        // final user = await createAccountWithEmail(
                        //   context,
                        //   emailTextController.text,
                        //   passwordTextController.text,
                        // );
                        // if (user == null) {
                        //   return;
                        // }
                        //
                        // final usersCreateData = createUsersRecordData(
                        //   email: emailTextController.text,
                        //   mobileNumber: mobileNumTextController.text,
                        // );
                        // await UsersRecord.collection
                        //     .doc(user.uid)
                        //     .update(usersCreateData);

                        // await sendEmailVerification();
                        // if (textController1.text.isEmpty) {
                        //   ScaffoldMessenger.of(context).showSnackBar(
                        //     SnackBar(
                        //       content: Text('Enter SMS verification code.'),
                        //     ),
                        //   );
                        //   return;
                        // }
                        // final phoneVerifiedUser = await verifySmsCode(
                        //   context: context,
                        //   smsCode: textController1.text,
                        // );
                        // if (phoneVerifiedUser == null) {
                        //   return;
                        // }


                        // await Navigator.push(
                        //   context,
                        //   MaterialPageRoute(
                        //     builder: (context) =>
                        //         OnboardingPersonallnfoWidget(),
                        //   ),
                        // );
                      },
                      text: 'Sign up',
                      options: FFButtonOptions(
                        width: 130,
                        height: 40,
                        color: Color(0xFFFFBC49),
                        textStyle: FlutterFlowTheme.subtitle2.override(
                          fontFamily: 'Roboto',
                          color: FlutterFlowTheme.dark400,
                        ),
                        borderSide: BorderSide(
                          color: Colors.transparent,
                          width: 1,
                        ),
                        borderRadius: 8,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}`

**Comment by ramluro1** [comment]
It seems to be working fine now. Not sure what I changed. Thank Aref

**Comment by ArefMozafari** [comment]
Anytime
