### ISSUE TITLE
onFail method

### ISSUE THREAD

**Issue by DarrenSanders123** [ArefMozafari/flutter_pw_validator#14]
Could you make an onFail option that runs every time the password doesn't match?

**Comment by ArefMozafari** [comment]
Sure

**Comment by DarrenSanders123** [comment]
Thank you so so so much, cause right now I have no way of knowing if after someone made a correct password and then removed chars, and it became false.

I use it to activate a button so like once the button activates when a correct password is put in, but then someone would remove or change the password and it's no longer correct it will still be active.

So this feature would help a lot😃

**Comment by ArefMozafari** [comment]
Now I've added it. I hope it will be useful to you.
