### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by lbk9** [ArefMozafari/flutter_pw_validator#16]
I have made use of the widget in a form field when a user is registering for a new account like so
```
class PasswordValidator extends StatelessWidget {
  final TextEditingController controller;
  final Function() onSuccess;
  const PasswordValidator({
    Key? key,
    required this.controller,
    required this.onSuccess,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(
        left: 20.0,
        top: 0.0,
        right: 20.0,
        bottom: 20.0,
      ),
      child: FlutterPwValidator(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height * 0.2,
        minLength: 6,
        specialCharCount: 1,
        uppercaseCharCount: 1,
        numericCharCount: 1,
        onSuccess: onSuccess,
        controller: controller,
      ),
    );
  }
}
```

During the API call, I set the page to be replaced with a ProgressIndicator. When the API calls fails, the user is kept on the same page and the ProgressIndicator is removed and text form fields are reset, in resetting the controller value that the password field is bound to, the following error is thrown
```
The following assertion was thrown while dispatching notifications for TextEditingController:
setState() called after dispose(): _FlutterPwValidatorState#85b38(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
```
The above error is also thrown anytime the password field is tapped or interacted with at all.

**Comment by ArefMozafari** [comment]
Would it be possible to include the page code as well?

**Comment by Money1998** [comment]
Hey @ArefMozafari and @lbk9 
I will help you with this Error and update this library according to your concern.

**Comment by ArefMozafari** [comment]
Great

**Comment by lbk9** [comment]
Sorry for ghosting this, github never notified me of any replies to this...

I think the setState in the widget state may just require a mounted check.

**Comment by ArefMozafari** [comment]
That's fine. Waiting to see @Money1998's solution before I fix this.

**Comment by Money1998** [comment]
@ArefMozafari issue Resolved, please merge code I have created one pull request
