### ISSUE TITLE
Can we show the password validator only when text field is on focus ?

### ISSUE THREAD

**Issue by dgurudot** [ArefMozafari/flutter_pw_validator#24]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/58795306/199368792-034b986b-c96a-4642-bba7-b23c0c3bb432.png">

Sharing an example where I have both Email and password and for a better user experience, I want to be able to show a password validator only when someone starts to type the password.

Moreover, is there a way to shift the validator to align perfectly under the field ?

**Comment by ArefMozafari** [comment]
For the first one, you can use an Opacity widget and set its value to 0.0 in the initial stage. Then add a listener to the field controller so you can change the opacity value to 1.0 when it has a text value.
And the second problem you can use the provided sizes in widget constructor.
