### ISSUE TITLE
we need key attribute, because i want to access the object functions like validate function from my Register button

### ISSUE THREAD

**Issue by MazenxELGayar** [ArefMozafari/flutter_pw_validator#25]
I tried so hard to add a key attribute to your code, but it didn't work out
I want a key attribute so I can access the validate function when I press my register button, so it won't be greyed out when I press register if he didn't type a password correctly

**Comment by ArefMozafari** [comment]
It would be helpful if it was implemented.
I'll get to it soon.

**Comment by ArefMozafari** [comment]
Done.
As requested, it has been added.
I hope you find it useful
