### ISSUE TITLE
Lowercase support

### ISSUE THREAD

**Issue by BrunoPereira-2331** [ArefMozafari/flutter_pw_validator#26]
The issue #20 was closed, lowercase support was discarded? 

it would be helpful to have this option

**Comment by ArefMozafari** [comment]
Unfortunately, I have a lot going on at the moment.

Would it be possible for you to add it and submit a PR for it?

**Comment by BrunoPereira-2331** [comment]
I created the PR, tested and i'm pretty sure everything its ok.

Thanks for the reply
