### ISSUE TITLE
Improving Documentation Score

### ISSUE THREAD

**Issue by adithyaakrishna** [ArefMozafari/flutter_pw_validator#3]
**Description:** The documnentation score of the package is 10/20 which can be improved by using documentation comments instead of normal comments

**Screenshot:**
![image](https://user-images.githubusercontent.com/23498248/112734321-08645d80-8f6b-11eb-8517-37005efa1248.png)

```
- Normal Comment: //
- Documentation Comment: ///
```

**Comment by ArefMozafari** [comment]
Thanks, it's merged.
